<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('articles')->insert([
            [
                'article_id' => 1,
                'title' => 'Systemic Brochure',
                'summary' => 'Brochure design for science festival',
                'content' => '<p>This brochure design is part of a suite of advertising materials that promote the Systemic science festival. These materials feature the complex visual identity that is an abstract grid of pathways representing choice and decision-making in designing complex systems.</p>',
                'created' => '2021-01-26 12:21:03',
                'category_id' => 1,
                'member_id' => 2,
                'image_id' => 1,
                'published' => 1,
                'seo_title' => 'systemic-brochure',
            ],
            [
                'article_id' => 2,
                'title' => 'Forecast',
                'summary' => 'Illustration for fashion magazine article',
                'content' => '<p>This drawing was commissioned by a fashion magazine for an article about spotting future trends. This piece uses luxury handbags to mimic clouds in a kind of fashion-based weather forecast-style graphic. The use of repetition and pattern highlights the potential power of a single prediction.</p>',
                'created' => '2021-01-28 19:44:03',
                'category_id' => 3,
                'member_id' => 2,
                'image_id' => 19,
                'published' => 1,
                'seo_title' => 'forecast',
            ],
            [
                'article_id' => 3,
                'title' => 'Swimming pool',
                'summary' => 'Architecture magazine photography',
                'content' => '<p>This photograph is one of a series commissioned for an article in an architectural magazine featuring swimming pools in private residences. The variety of locations shared a similar mid-century modern aesthetic and were rendered using a grainy, black and white film stock.</p>',
                'created' => '2021-02-02 09:45:52',
                'category_id' => 4,
                'member_id' => 1,
                'image_id' => 3,
                'published' => 1,
                'seo_title' => 'swimming-pool',
            ],
            [
                'article_id' => 4,
                'title' => 'Walking Birds',
                'summary' => 'Artwork for music video',
                'content' => '<p>The brief for this music video was to combine a psychedelic sixties vibe with a granola-brown seventies aesthetic and morph it into a Sesame Street-style animation. With over two million views online, the artwork successfully promoted the song across multiple social media channels.</p>',
                'created' => '2021-02-12 11:05:35',
                'category_id' => 3,
                'member_id' => 3,
                'image_id' => 4,
                'published' => 1,
                'seo_title' => 'walking-birds',
            ],
            [
                'article_id' => 5,
                'title' => 'Sisters',
                'summary' => 'Editorial graphics for psychology article',
                'content' => '<p>The article that these illustrations accompany highlights the changing landscape of family connections in the modern age as compared to fifty years ago. The brief was to visualize the interpersonal drift caused by increased dispersement of communities across the globe.</p>',
                'created' => '2021-02-26 15:31:16',
                'category_id' => 3,
                'member_id' => 3,
                'image_id' => 5,
                'published' => 1,
                'seo_title' => 'sisters',
            ],
            [
                'article_id' => 6,
                'title' => 'Micro-Dunes',
                'summary' => 'Photography for scientific journal',
                'content' => '<p>This photograph was commissioned to accompany a scientific article about micro-ecologies in the coastal environment. Due to the miniature scale of the subject matter, a macro lens was used to capture the fine detail. It was shot on location on the mid-north coast of Australia.</p>',
                'created' => '2021-03-02 21:02:47',
                'category_id' => 4,
                'member_id' => 1,
                'image_id' => 6,
                'published' => 1,
                'seo_title' => 'micro-dunes',
            ],
            [
                'article_id' => 7,
                'title' => 'Milk Beach Website',
                'summary' => 'Website for music series',
                'content' => '<p>Using the imagery commissioned for the album artwork, this website aims to provide a simple channel for users to listen to the music digitally. Care was taken to ensure fans of the music could connect with the brand and keep updated on future offerings.</p>',
                'created' => '2021-03-06 10:16:22',
                'category_id' => 2,
                'member_id' => 1,
                'image_id' => 7,
                'published' => 1,
                'seo_title' => 'milk-beach-website',
            ],
            [
                'article_id' => 8,
                'title' => 'Wellness App',
                'summary' => 'App for health facility',
                'content' => '<p>The Wellness chain of health facilities required an app that allowed members to view and book classes. The existing brand style guide defined the overall look and feel of the site with the main goal of the design to be as minimalistic as possible.</p>',
                'created' => '2021-03-12 14:45:49',
                'category_id' => 2,
                'member_id' => 2,
                'image_id' => 8,
                'published' => 1,
                'seo_title' => 'wellness-app',
            ],
            [
                'article_id' => 9,
                'title' => 'Milk Beach Music',
                'summary' => 'Photography for a music series',
                'content' => '<p>The music label that released this series wanted to capture the beach that inspired its creation. A number of photographs (including panoramic views and close-ups) were shot on location at Milk Beach in Sydney, Australia. They were given a duotone appearance in post-production.</p>',
                'created' => '2021-03-12 17:09:40',
                'category_id' => 4,
                'member_id' => 1,
                'image_id' => 9,
                'published' => 1,
                'seo_title' => 'milk-beach-music',
            ],
            [
                'article_id' => 10,
                'title' => 'Polite Society Mural',
                'summary' => 'Large-scale illustrations for fashion label',
                'content' => '<p>This is one of several illustrations commissioned by fashion label, Polite Society, to decorate their new autumn-winter collection displays. Appearing in various forms (such as murals, digital projections, and in print) they represent the modern aesthetic of the latest range.</p>',
                'created' => '2021-03-16 14:14:40',
                'category_id' => 3,
                'member_id' => 1,
                'image_id' => 10,
                'published' => 1,
                'seo_title' => 'polite-society-mural',
            ],
            [
                'article_id' => 11,
                'title' => 'Stargazer Website and App',
                'summary' => 'Website and app design for music festival',
                'content' => '<p>The Stargazer music festival website uses a highly typographic treatment to communicate the high calbre performers who will be appearing. As well as allowing users to view the line-up and purchase tickets, the website also allows them to plan their itineraries and book food.</p>',
                'created' => '2021-03-17 18:01:19',
                'category_id' => 2,
                'member_id' => 3,
                'image_id' => 11,
                'published' => 1,
                'seo_title' => 'stargazer-website-and-app',
            ],
            [
                'article_id' => 12,
                'title' => 'The Ice Palace',
                'summary' => 'Book cover design',
                'content' => '<p>This cover is for a Chimney Press reissue of the Norwegian classic novel, The Ice Palace. The design reflects the concise style of the writing and the sense of unease that appears throughout, almost as its own frozen character. The binding uses linen and a thick cover keeps its secrets close to its chest.</p>',
                'created' => '2021-03-20 11:24:52',
                'category_id' => 1,
                'member_id' => 2,
                'image_id' => 12,
                'published' => 1,
                'seo_title' => 'the-ice-palace',
            ],
            [
                'article_id' => 13,
                'title' => 'Chimney Press Website',
                'summary' => 'Website for book publisher',
                'content' => '<p>This design was based on extensive research into the perception of the Chimney Press brand across multiple channels. The insights gained showed that customers were very keen to keep informed on new and upcoming releases and also to share this information throughout their social networks.</p>',
                'created' => '2021-03-21 08:44:01',
                'category_id' => 2,
                'member_id' => 2,
                'image_id' => 13,
                'published' => 1,
                'seo_title' => 'chimney-press-website',
            ],
            [
                'article_id' => 14,
                'title' => 'Milk Beach Album Cover',
                'summary' => 'Packaging for music series',
                'content' => '<p>Having commissioned a number of photographs of the intertidal rocks that adorn the eponymous Milk Beach, this packaging creates a beautiful and serene context for the hugely successful music series. Natural, recycled cardstocks and gentle colorways were used throughout.</p>',
                'created' => '2021-03-27 13:15:20',
                'category_id' => 1,
                'member_id' => 1,
                'image_id' => 14,
                'published' => 1,
                'seo_title' => 'milk-beach-album-cover',
            ],
            [
                'article_id' => 15,
                'title' => 'Seascape',
                'summary' => 'Photograph for art exhibition',
                'content' => '<p>This shot of tbe sea at Margate was included in a group show at the Turner Contemporary art gallery in Kent, England. Printed at a large scale, the serene viewpoint reveals a timeless beauty to the briny waters that have lured Londoners to it for centuries.</p>',
                'created' => '2021-04-03 19:36:08',
                'category_id' => 4,
                'member_id' => 2,
                'image_id' => 15,
                'published' => 1,
                'seo_title' => 'seascape',
            ],
            [
                'article_id' => 16,
                'title' => 'Polite Society Website',
                'summary' => 'Website for fashion label',
                'content' => '<p>The Polite Society website was rebuilt from the ground up with a complete evaluation of the old version and adjustments to the new user experience to respond to it. As well as working on multiple devices, a new back-end was built to encompass the expanding nature of the company.</p>',
                'created' => '2021-04-06 10:21:44',
                'category_id' => 2,
                'member_id' => 1,
                'image_id' => 16,
                'published' => 1,
                'seo_title' => 'polite-society-website',
            ],
            [
                'article_id' => 17,
                'title' => 'Snow Search',
                'summary' => 'Graphics for mobile game',
                'content' => '<p>These illustrations of a young boy and his dog formed the basis for a highly successful animated game called Snow Search. The game, which was designed for mobile devices, received several awards for game design and mechanics. More illustration work is currently underway for a sequel.</p>',
                'created' => '2021-04-08 08:46:31',
                'category_id' => 3,
                'member_id' => 3,
                'image_id' => 17,
                'published' => 1,
                'seo_title' => 'snow-search',
            ],
            [
                'article_id' => 18,
                'title' => 'Floral Website',
                'summary' => 'Website for florist',
                'content' => '<p>This florist in Brooklyn required an updated website to support the expanding scope of their business. Working in association with a stylist and a photographer, we created a pleasant and straightforward user experience. Since the relaunch, online enquiries have increased.</p>',
                'created' => '2021-04-08 17:05:19',
                'category_id' => 2,
                'member_id' => 1,
                'image_id' => 18,
                'published' => 1,
                'seo_title' => 'floral-website',
            ],
            [
                'article_id' => 19,
                'title' => 'Abandoned Industry',
                'summary' => 'Photograph for magazine feature',
                'content' => '<p>This photograph of old industrial equipment on a disused dock appeared alongside an essay in a magazine about urban-planning and regeneration. The brief was to consider the visual beauty inherent in decay and inspire readers to embrace sustainable idealogies within the contemporary landscape.</p>',
                'created' => '2021-04-11 10:52:02',
                'category_id' => 4,
                'member_id' => 2,
                'image_id' => 21,
                'published' => 1,
                'seo_title' => 'abandoned-industry',
            ],
            [
                'article_id' => 20,
                'title' => 'Chimney Business Cards',
                'summary' => 'Stationery design for publishing company',
                'content' => '<p>Along with several other items of branded stationery, Chimney Press required new business cards for their expanding office staff. In keeping with their company mission of re-releasing older book titles, a clean and vintage-inspired aesthetic informed the otherwise modern design.</p>',
                'created' => '2021-04-15 09:04:39',
                'category_id' => 1,
                'member_id' => 2,
                'image_id' => 20,
                'published' => 1,
                'seo_title' => 'chimney-business-cards',
            ],
            [
                'article_id' => 21,
                'title' => 'Stargazer',
                'summary' => 'Illustrations for music festival',
                'content' => '<p>A series of illustrations were commissioned for the Stargazer music festivals range of promotional materials. A creative choice was made not to portray the night sky itself (as in previous years) but to focus on the beauty and wonder inherent in the patrons themselves.</p>',
                'created' => '2021-04-19 18:08:11',
                'category_id' => 3,
                'member_id' => 3,
                'image_id' => 23,
                'published' => 1,
                'seo_title' => 'stargazer',
            ],
            [
                'article_id' => 22,
                'title' => 'Polite Society Posters',
                'summary' => 'Poster designs for fashion label',
                'content' => '<p>These posters were designed to increase brand awareness in fashion districts as part of an international campaign ahead of the upcoming autumn-winter season. The client required something aesthetically modern that introduced the vibrant palette of the new collection.</p>',
                'created' => '2021-04-22 07:49:27',
                'category_id' => 1,
                'member_id' => 1,
                'image_id' => 2,
                'published' => 1,
                'seo_title' => 'Polite-Society-Posters',
            ],
            [
                'article_id' => 23,
                'title' => 'Golden Brown',
                'summary' => 'Photograph for interior design book',
                'content' => '<p>This photograph is one of a range that appears in a book about interior design called Golden Brown. The interiors featured in the book show the current trend for looking back to the 1970\'s and the colour treatment of the photography reflects this warm, earthy palette.</p>',
                'created' => '2021-04-25 13:51:19',
                'category_id' => 4,
                'member_id' => 3,
                'image_id' => 22,
                'published' => 1,
                'seo_title' => 'golden-brown',
            ],
            [
                'article_id' => 24,
                'title' => 'Travel Guide',
                'summary' => 'Book design for series of travel guides',
                'content' => '<p>The best-selling travel guide series, <strong>Featherview</strong>, required a refreshed look and feel for their latest series of books covering the Asian region. They were after a clean and concise solution - a versatile design that could accommodate both the coffee table and the backpack.</p>',
                'created' => '2021-04-25 19:11:42',
                'category_id' => 1,
                'member_id' => 1,
                'image_id' => 24,
                'published' => 1,
                'seo_title' => 'travel-guide',
            ],
            [
                'article_id' => 25,
                'title' => 'Buddha',
                'summary' => 'Photograph for magazine article',
                'content' => '<p>The article this photograph accompanies is about the growing popularity of mindfulness meditation in the mental health industry today. The text traces the history of mindfulness back to its Buddhist origins.</p>',
                'created' => '2021-08-03 09:30:19',
                'category_id' => 4,
                'member_id' => 12,
                'image_id' => 25,
                'published' => 1,
                'seo_title' => 'buddha',
            ],
            [
                'article_id' => 26,
                'title' => 'Faces in the Water',
                'summary' => 'Book cover design',
                'content' => '<p>Chimney Press requested a book cover design for this poignant portrayal of a woman\'s experience in a psychiatric facility. The typographic treatment intends to mimic the movement of water across the surface of a body of water and I feel it resonates with the highly poetic and sensitive subject matter.</p>',
                'created' => '2021-08-03 12:11:24',
                'category_id' => 1,
                'member_id' => 8,
                'image_id' => 26,
                'published' => 1,
                'seo_title' => 'faces-in-the-water',
            ],
            [
                'article_id' => 27,
                'title' => 'Salmon',
                'summary' => 'Photograph for restaurant review',
                'content' => '<p>This photograph was part of a series shot at a new seafood restaurant to appear alongside a review in the New York Times. Care was taken to ensure the series reflected the fresh, organic menu and "clean-eating" minimalist aesthetic of the restaurant itself.</p>',
                'created' => '2021-08-03 09:23:07',
                'category_id' => 4,
                'member_id' => 10,
                'image_id' => 27,
                'published' => 1,
                'seo_title' => 'salmon',
            ],
            [
                'article_id' => 28,
                'title' => 'Quiet',
                'summary' => 'Book cover design',
                'content' => '<p>This cover design is for a book about silent movies and is based on the dialogue boards they used. The card stock for the cover is designed to look slightly old and dusty and uses rough-textured recycled materials to give the ink a nice matte effect.</p>',
                'created' => '2021-08-03 11:21:04',
                'category_id' => 1,
                'member_id' => 7,
                'image_id' => 28,
                'published' => 1,
                'seo_title' => 'quiet',
            ],
            [
                'article_id' => 29,
                'title' => 'Quiet Invite',
                'summary' => 'Invitation design for documentary',
                'content' => '<p>This invitation was designed for the world premiere and launch party of a new documentary by Claude Dupont titled "Quiet: A Silent Film History." It was important to make it visually cohesive with the book that I also designed for the same feature.</p>',
                'created' => '2021-08-03 11:26:29',
                'category_id' => 1,
                'member_id' => 7,
                'image_id' => 29,
                'published' => 1,
                'seo_title' => 'quiet-invite',
            ],
            [
                'article_id' => 30,
                'title' => 'Museum',
                'summary' => 'Photography for a museum',
                'content' => '<p>The MAXII museum (Museo Nazionale delle Arti del XXI Secolo) in Rome, Italy was designed by Zaha Hadid and is dedicated to contemporary art and architecture. This assignment was to capture the neon installation on its exterior by Italian artist, Maurizio Nannucci.</p>',
                'created' => '2021-08-03 09:06:12',
                'category_id' => 4,
                'member_id' => 5,
                'image_id' => 30,
                'published' => 1,
                'seo_title' => 'museum',
            ],
            [
                'article_id' => 31,
                'title' => 'New Forest',
                'summary' => 'Website design for artist retreat',
                'content' => '<p>This website for a retreat in the New Forest was designed to inspire artists and writers to consider it the perfect location in which to create. The layout is clean and classical to allow the photography to communicate the beautiful surroundings.</p>',
                'created' => '2021-08-04 10:04:37',
                'category_id' => 2,
                'member_id' => 7,
                'image_id' => 31,
                'published' => 1,
                'seo_title' => 'new-forest',
            ],
        ]);
    }
}